name: 🚀 Deploy local (dev)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-local:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4

      - name: 🔐 Export VARS and SECRETS in a temp .env file
        run: |
          echo "" > "$GITHUB_WORKSPACE/secrets.env"
          printenv | grep sort >> "$GITHUB_WORKSPACE/secrets.env" || true

      - name: 🛠️ Generate config.php files
        run: |
          mkdir -p admin crm
          echo "<?php" > config.php
          echo "<?php" > admin/config.php
          echo "<?php" > crm/config.php
          
          echo "define('DB_PREFIX', '');" >> config.php
          echo "define('DB_PREFIX', '');" >> admin/config.php
          echo "define('DB_PREFIX', '');" >> crm/config.php
          
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            IFS='_' read -r env context name <<< "$key"
            const="${key#${env}_${context}_}"

            case "$context" in
              ROOT)
                echo "define('${const}', '${value}');" >> config.php
                ;;
              ADMIN)
                echo "define('${const}', '${value}');" >> admin/config.php
                ;;
              CRM)
                echo "define('${const}', '${value}');" >> crm/config.php
                ;;
            esac
          done < "$GITHUB_WORKSPACE/secrets.env"

      - name: 🧾 Mostrar contenido de los archivos config generados
        run: |
          echo "🧾 config.php (ROOT)"
          cat config.php || echo "❌ No encontrado"
          echo ""
          echo "🧾 admin/config.php (ADMIN)"
          cat admin/config.php || echo "❌ No encontrado"
          echo ""
          echo "🧾 crm/config.php (CRM)"
          cat crm/config.php || echo "❌ No encontrado"
          cat $GITHUB_WORKSPACE/secrets.env
