name: 🚀 Deploy local (dev)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-local:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4
      - name: Create temporary .env FILE
        run: |
          echo "" > "$GITHUB_WORKSPACE/secrets.env"

      - name: 🔐 Export SECRETS in the temporary .env
        env:
          DEV_ROOT_APIKEY_EV: ${{ secrets.DEV_ROOT_APIKEY_EV }}
        run: |
          printenv | sort >> "$GITHUB_WORKSPACE/secrets.env" || true

      - name: 🔐 Export VARS in a the temporary .env file
        env:
          DEV_ROOT_TEST_VARIABLE_ENV: ${{ vars.DEV_ROOT_TEST_VARIABLE_ENV }}
        run: |
          printenv | sort >> "$GITHUB_WORKSPACE/secrets.env" || true

      - name: 🛠️ Generate config.php files
        run: |
          mkdir -p admin crm
          echo "<?php" > config.php
          echo "<?php" > admin/config.php
          echo "<?php" > crm/config.php
          
          echo "define('DB_PREFIX', '');" >> config.php
          echo "define('DB_PREFIX', '');" >> admin/config.php
          echo "define('DB_PREFIX', '');" >> crm/config.php
          
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            IFS='_' read -r env context name <<< "$key"
            const="${key#${env}_${context}_}"

            case "$context" in
              ROOT)
                echo "define('${const}', '${value}');" >> config.php
                ;;
              ADMIN)
                echo "define('${const}', '${value}');" >> admin/config.php
                ;;
              CRM)
                echo "define('${const}', '${value}');" >> crm/config.php
                ;;
            esac
          done < "$GITHUB_WORKSPACE/secrets.env"

      - name: 🧾 Mostrar contenido de los archivos config generados
        run: |
          echo "🧾 config.php (ROOT)"
          cat config.php || echo "❌ No encontrado"
          echo ""
          echo "🧾 admin/config.php (ADMIN)"
          cat admin/config.php || echo "❌ No encontrado"
          echo ""
          echo "🧾 crm/config.php (CRM)"
          cat crm/config.php || echo "❌ No encontrado"
          cat $GITHUB_WORKSPACE/secrets.env

      - name: 📂 Verifica contenido antes de subir
        run: |
          echo "Contenido de secrets.env:"
          cat $GITHUB_WORKSPACE/secrets.env || echo "❌ secrets.env no existe"

          echo "Archivos disponibles:"
          ls -l

      - name: 📤 Subir secrets.env como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: deploy-outputs
          path: |
            $GITHUB_WORKSPACE/secrets.env
            $GITHUB_WORKSPACE/config.php
            $GITHUB_WORKSPACE/admin/config.php
            $GITHUB_WORKSPACE/crm/config.php